[tool.poetry]
name = "bibx"
version = "0.1.0"
description = "Python bibliometric tools."
authors = ["Core of Science Team <technology@coreofscience.org>"]
license = "MIT"
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.8"
bibtexparser = "^1.4.0"
networkx = "^3.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pytest = "^7.2.0"
isort = "^5.12.0"
pre-commit = "^2.20.0"
ruff = "^0.0.254"

[tool.ruff]
ignore = ["E501"]
